version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "mongodb"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:3.6.3
    volumes:
      - ./data:/usr/src/app/data/db
    ports:
      - "27017:27017"